thresholds:
  # Platform
  default:
    # CNI
    default:
      pod_start_latency:
        great_low: 0
        great_high: 1000000
        poor_high: 2000000
        bad_high: -1 # Max value
      etcd_health:
        great_low: 0
        great_high: 0.5
        poor_high: 5
        bad_high: -1 # Max value
      etcd_disk_sync_duration:
        great_low: 0
        great_high: 5000
        poor_high: 15000
        bad_high: -1 # Max value
      etcd_leader_change_rate:
        great_low: 0
        great_high: 0.5
        poor_high: 5
        bad_high: -1 # Max value
